---
name: Push

"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: cachix/install-nix-action@v31
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any git hooks
        run: devenv test

  generate-readme:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v21
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: mkdir newreadme
      - run: (grep -B 99999 "BEGIN SERVICE LIST" README.md && nix eval --offline --raw --file bin/generateServicesTable.nix && grep -A 99999 "END SERVICE LIST" README.md) > newreadme/README.md
      - uses: actions/upload-artifact@v4
        with:
          name: new-readme
          path: newreadme

  push-readme:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - lint
      - generate-readme
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: new-readme
          path: newreadme
      - run: mv newreadme/README.md README.md
      - name: Commit and push README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff-index --quiet HEAD || git commit -m "chore: Generate README.md"
          git push

  tests:
    name: Flake Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dynamically update flake input URL
        run: |
          # Replace with your repository details
          DEFAULT_URL="github:skiinganchor/config"
          FLAKE_FOLDER="flakes"

          FLAKE_FILE="${FLAKE_FOLDER}/flake.nix"

          # Default to the current repo and branch (for pushes)
          REPO_SLUG="${{ github.repository }}"
          BRANCH_NAME="${{ github.ref_name }}"

          # If the trigger is a pull request, use its specific context
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Pull request event detected. Using PR head context."
            REPO_SLUG="${{ github.event.pull_request.head.repo.full_name }}"
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          fi

          # The final URL points to the correct repository and branch
          FINAL_URL="github:${REPO_SLUG}/${BRANCH_NAME}"

          echo "Source Repository: ${REPO_SLUG}"
          echo "Source Branch:     ${BRANCH_NAME}"
          echo "Final Flake URL:   ${FINAL_URL}"

          # Replace the default URL with the dynamically constructed one
          sed -i "s|${DEFAULT_URL}|${FINAL_URL}|" "$FLAKE_FILE"

          echo "--- Verifying ${FLAKE_FILE} modification --"
          cat "$FLAKE_FILE"
          echo "-------------------------------------------"

      - name: Check flake
        run: |
          cd "$FLAKE_FOLDER"
          nix flake check
